### ISSUE TITLE
about vedai dataset

### ISSUE THREAD

**Issue by 4everImmortality** [iMoonLab/Hyper-YOLO#7]
dear author
It seems that there's no dataset yaml from the source code
how can i train vedai dataset? is there any way resembles like superyolo when creating dataset?

**Comment by jianganghuang** [comment]
Thank you for bringing this to our attention. It appears that we may have inadvertently omitted the dataset yaml file during the upload process. We have since rectified this and have included the dataset yaml file in the ‘ultralytics/cfs/datasets’ directory. 

As for training the VEDAI remote sensing dataset, you can convert the labels to the YOLO format and configure the appropriate dataset yaml file accordingly.

**Comment by 4everImmortality** [comment]
> Thank you for bringing this to our attention. It appears that we may have inadvertently omitted the dataset yaml file during the upload process. We have since rectified this and have included the dataset yaml file in the ‘ultralytics/cfs/datasets’ directory.
> 
> As for training the VEDAI remote sensing dataset, you can convert the labels to the YOLO format and configure the appropriate dataset yaml file accordingly.

Thanks
